---
services:
  nginx:
    image: jc21/nginx-proxy-manager:2.15.1
    container_name: nginx-proxy-manager
    restart: always
    volumes:
      - ${DOCKER_DATA}/nginxproxymanager/data:/data
      - ${DOCKER_DATA}/nginxproxymanager/etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 81:81
      - 443:443
    networks:
      - server-backend

networks:
  server-backend:
    external: true
