---
services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    hostname: myspeed
    restart: always
    volumes:
      - ${DOCKER_DATA}/myspeed/data:/myspeed/data
    # ports:
    #   - 5216:5216
    networks:
      - server-backend

networks:
  server-backend:
    external: true
