listen_addresses = '*'
port = 5432

# Shared libraries to preload at server start
shared_preload_libraries = 'vchord'

# TLS
ssl = on
ssl_cert_file = '/certs/server-cert.pem'
ssl_key_file = '/certs/server-key.pem'
ssl_ca_file = '/certs/ca.pem'
ssl_min_protocol_version = 'TLSv1.3'

# Authentication
password_encryption = 'scram-sha-256'

# pg_hba
hba_file = '/etc/postgresql/pg_hba.conf'

# pg_ident
ident_file = '/etc/postgresql/pg_ident.conf'
