---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: []
#           scheme: http
#           timeout: 10s
#           api_version: v1
scrape_configs:
  - job_name: 'statsd-exporter'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['statsd-exporter:9102']
  - job_name: 'wud-teste'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['wud:3000']
