---
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    volumes:
      - transmission_config:/config
      - ${MEDIA}/downloads:/downloads
      - ${MEDIA}/watch:/watch
    environment:
      - PUID=${UID}
      - PGID=${UIG}
      - TZ=${TZ}
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    ports:
      # - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - server-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.entrypoints=https
      - traefik.http.routers.transmission.rule=Host(`transmission.${SERVER}.${DOMAIN}`)
      - traefik.http.routers.transmission.tls=true
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.tls.certresolver=transmission

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    volumes:
      - ${DOCKER_DATA}/jellyfin/config:/config
      - ${MEDIA}:/Media
      - ${GALLERY}:/Gallery
    environment:
      - PUID=${UID}
      - PGID=${UIG}
      - TZ=${TZ}
    ports:
      # - 8096:8096/tcp
      # - 8920:8920/tcp
      - 7359:7359/tcp
      - 1900:1901/tcp
    networks:
      - server-backend
    devices:
      - /dev/dri:/dev/dri
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${SERVER}.${DOMAIN}`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin.tls.certresolver=jellyfin

networks:
  server-backend:
    external: true

volumes:
  transmission_config:
