---
- name: Configure UFW Firewall
  hosts: "{{ hosts | d([]) }}"
  become: true

  vars:
    tailscale_interface: tailscale0
    local_interface: "{{ default_interface | default('eth0') }}"
    public_tcp_ports:
      - 80
      - 443
    local_tcp_ports:
      - 22
      - 53
      - 445
      # - 1883 mqtt port
      - 2049
      - 8883  # mqtt tls port
      - 21027
      - 22000
    local_udp_ports:
      - 53
      - 2049
      - 21027
      - 22000

  tasks:
    - name: Install UFW
      package:
        name: ufw
        state: present

    - name: Reset UFW to defaults (idempotent baseline)
      ufw:
        state: reset

    - name: Set UFW default incoming policy to deny
      ufw:
        default: deny
        direction: incoming
        comment: Default deny incoming

    - name: Set UFW default outgoing policy to allow
      ufw:
        default: allow
        direction: outgoing
        comment: Default allow outgoing

    - name: Allow all traffic on Tailscale interface
      ufw:
        rule: allow
        interface: "{{ tailscale_interface }}"
        direction: in
        comment: Allow all traffic on Tailscale interface

    - name: Allow Public TCP ports
      ufw:
        rule: allow
        port: "{{ item | string }}"
        proto: tcp
        comment: "Allow public TCP port: {{ item }}"
      loop: "{{ public_tcp_ports }}"

    - name: Allow Local TCP ports
      ufw:
        rule: allow
        port: "{{ item | string }}"
        proto: tcp
        interface: "{{ local_interface }}"
        direction: in
        comment: "Allow local TCP port: {{ item }}"
      loop: "{{ local_tcp_ports }}"

    - name: Allow Local UDP ports
      ufw:
        rule: allow
        port: "{{ item | string }}"
        proto: udp
        interface: "{{ local_interface }}"
        direction: in
        comment: "Allow local UDP port: {{ item }}"
      loop: "{{ local_udp_ports }}"

    - name: Enable UFW
      ufw:
        state: enabled
