---
apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true

  - name: loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    editable: true
    jsonData:
      tlsSkipVerify: true

  - name: redis
    type: redis-datasource
    access: proxy
    url: ${REDIS_URL}
    editable: true

  - name: mongodb
    type: haohanyang-mongodb-datasource
    access: proxy
    url: ${MONGO_URL}
    editable: true

  - name: influxdb
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    editable: true
    jsonData:
      version: Flux
      organization: ${INFLUX_ORG}
      defaultBucket: ${INFLUX_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}

  - name: tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    editable: true
    jsonData:
      tlsSkipVerify: true

  - name: mqtt
    type: grafana-mqtt-datasource
    editable: true
    jsonData:
      uri: $MQTT_URL
      username: $MQTT_USER
      clientID: grafana
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
    secureJsonData:
      password: $MQTT_PASS
