---
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    hostname: it-tools
    restart: always
    ports:
      - 1020:80
    networks:
      - server-backend

networks:
  server-backend:
    external: true
