---
services:
  it-tools:
    image: corentinth/it-tools:latest
    container_name: it-tools
    restart: always
    # ports:
    #   - 80:80
    networks:
      - server-backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.it-tools.entrypoints=https
      - traefik.http.routers.it-tools.rule=Host(`it-tools.${SERVER}.${DOMAIN}`)
      - traefik.http.routers.it-tools.tls=true
      - traefik.http.services.it-tools.loadbalancer.server.port=80
      - traefik.http.routers.it-tools.tls.certresolver=it-tools
      - traefik.http.routers.it-tools.middlewares=authentik@file

networks:
  server-backend:
    external: true
