---
datasources:
  postgres:
    url: jdbc:postgresql://${KESTRA_POSTGRES_IP}:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: "{{ secret(KESTRA_POSTGRES_PASS) }}"
kestra:
  server:
    basicAuth:
      enabled: false
      username: "admin@kestra.io"
      password: kestra
  repository:
    type: postgres
  # storage:
  #   type: local
  #   local:
  #     basePath: "/app/storage"
  storage:
    type: s3
    s3:
      endpoint: ${KESTRA_MINIO_ENDPOINT}
      accessKey: ${KESTRA_MINIO_ACCESS_KEY}
      secretKey: ${KESTRA_MINIO_SECRET_KEY}
      region: "us-east-1"
      bucket: "kestra"
      forcePathStyle: "true"
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/
  templates:
    enabled: false
  tutorialFlows:
    enabled: false
  traces:
    root: DEFAULT
otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: https://lokigrpc.falcon.${DOMAIN}
