---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: always
    environment:
      - PUID=${UID}
      - PGID=${UIG}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - PROXY_DOMAIN=${DOMAIN}
      - DEFAULT_WORKSPACE=/docker/projects
    volumes:
      - ${DOCKER_DATA}/code-server/config:/config
      - ${PROJECTS_PATH}:/docker/projects
    ports:
      - 8443:8443
    networks:
      - server-backend


networks:
  server-backend:
    external: true
