version: "3"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /opt/duplicati_data:/config
      - /backups:/backups
      - /drive:/source
    ports:
      - 8200:8200
    restart: always
