---
http:
  routers:
    pihole-shuttle:
      rule: "Host(`pihole.shuttle.${DOMAIN}`)"
      service: pihole-shuttle
      priority: 1001
      entrypoints:
        - http
        - https
      tls:
        certResolver: cloudflare
  services:
    pihole-shuttle:
      loadBalancer:
        servers:
          - url: "https://${PIHOLE_HOST}:8443"
