---
http:
  routers:
    pihole-falcon:
      rule: "Host(`pihole.falcon.${DOMAIN}`)"
      service: pihole-falcon
      priority: 1002
      entrypoints:
        - http
        - https
      tls:
        certResolver: cloudflare
  services:
    pihole-falcon:
      loadBalancer:
        servers:
          - url: "https://${PIHOLE_HOST}:8443"
