---
- name: Deploy compose service
  hosts: "{{ hosts | default([]) }}"
  become: true
  vars:
    compose_path: "{{ remote_path | default('~/compose') }}"
  collections:
    - community.docker

  tasks:
    - name: destroy docker-compose project
      community.docker.docker_compose_v2:
        project_src: "{{ compose_path }}/{{ compose_name }}"
        files:
          - docker-compose.yaml
        state: absent
        remove_orphans: true
        remove_volumes: true
