---
- name: Docker Certs enable
  hosts: "{{ hosts | default([]) }}"
  become: true
  vars:
  collections:
    - community.docker

  tasks:
    - name: Check if docker certs are existing
      ansible.builtin.stat:
        path: "{{ certs_path }}"
      register: certs_dir

    - name: Fail if docker certs are not existing
      ansible.builtin.fail:
        msg: "Docker certificates are not existing in {{ certs_path }}."
      when: not certs_dir.stat.exists

    - name: Check if docker_api_host is a valid ip address
      ansible.builtin.assert:
        that:
          - docker_api_host is match("^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$")
        fail_msg: "docker_api_host is not a valid ip address."
        success_msg: "docker_api_host is a valid ip address."

    - name: Ensure docker systemd override directory exists
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'

    - name: Configure docker daemon to expose TLS API
      ansible.builtin.copy:
        path: /etc/systemd/system/docker.service.d/override.conf
        mode: '0644'
        content: |
          [Service]
          ExecStart=
          ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://{{ docker_api_host }}:2376 --tlsverify --tlscacert={{ certs_path }}/ca.pem --tlscert={{ certs_path }}/server-cert.pem --tlskey={{ certs_path }}/server-key.pem

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart docker daemon
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true
