---
services:
  cloudflared:
    image: cloudflare/cloudflared:2026.8.2
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TUNNEL_TOKEN}
    networks:
      - server-backend

networks:
  server-backend:
    external: true
